
// Generated by https://quicktype.io

export interface Zoemd {
    /** 影片資訊。 */
    metadata: Metadata;

    /** 快照。 */
    screenshots: number[];
}

export interface Metadata {
    duration:   number;
    width:      number;
    height:     number;
    codec_name: string;
}
